# Ansible Variables for provision_vms.yml

# General Proxmox Configuration for creating template
vm_id: 9110
vm_name: "debian12-cloud"
memory: 2048
bridge: "vmbr0"
disk_size: "6G"
storage: "jaro-zfs"
ssh_key_path: "/root/ansible-key.pub"
image_format: raw
vm_image: "debian-12-genericcloud-amd64.$image_format"
cloud_image_url: "https://cloud.debian.org/images/cloud/bookworm/$vm_image"

# Cloud-init configuration type
citype: "cidata"

# API Configuration
api_user: "ansible@pam"
node: "jaro"

# Variables for Ceph VMs
ceph_vms:
  - { vmid: 101, name: "ceph-cluster1", storage: "ceph-storage" }
  - { vmid: 102, name: "ceph-cluster2", storage: "ceph-storage" }
  - { vmid: 103, name: "ceph-cluster3", storage: "ceph-storage" }

# Variables for Docker VM
docker_vm:
  vmid: 104
  name: "docker-host"
  storage: "local-zfs"  # Or "local-lvm" if you prefer LVM for Docker
  disk_size: 8G
  template: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"
