# Ansible Variables for provision_vms.yml

# General Proxmox Configuration for creating template
vm_id: 9110
vm_name: "debian12-cloud"
memory: 2048
bridge: "vmbr0"
disk_size: "6G"
storage: "jaro-zfs"
disk_partition: /dev/sdb1
ssh_key_path: "/root/.ssh/ansible-key.pub"
image_format: raw
vm_image: "debian-12-genericcloud-amd64.{{ image_format }}"
cloud_image_url: "https://cloud.debian.org/images/cloud/bookworm/latest/{{ vm_image }}"

# Cloud-init configuration type
citype: "cidata"

# API Configuration
api_user: "ansible@pam"
node: "jaro"

# Variables for Ceph VMs
ceph_vms:
  - { name: "ceph-cluster1", storage: "jaro-zfs", clone: "{{ vm_name }}" }
  - { name: "ceph-cluster2", storage: "jaro-zfs", clone: "{{ vm_name }}" }
  - { name: "ceph-cluster3", storage: "jaro-zfs", clone: "{{ vm_name }}" }



# Variables for Docker VM
docker_vm:
  name: "docker-host"
  storage: "jaro-zfs"  # Or "local-lvm" if you prefer LVM for Docker
  disk_size: 8G
  clone: "{{ vm_name }}"  # Name of the template for Docker VM

