- name: Configure Ceph Cluster
  hosts: ceph_nodes
  become: true
  vars:
    ceph_release: "octopus"
  tasks:
    - name: Install Ceph packages
      apt:
        name: "ceph, ceph-common, ceph-fs-common"
        state: present
        update_cache: yes

    - name: Configure Ceph repository
      apt_repository:
        repo: "deb http://download.ceph.com/debian-{{ ceph_release }}/ {{ ansible_lsb.codename }} main"
        state: present

    - name: Install Ceph monitor and OSD
      command: ceph-deploy new {{ inventory_hostname }}
      args:
        creates: /etc/ceph/ceph.conf

    - name: Deploy the monitor
      command: ceph-deploy mon create-initial
      args:
        chdir: /root

    - name: Deploy the OSDs
      command: ceph-deploy osd create --data /dev/sdb {{ inventory_hostname }}
      args:
        chdir: /root

    - name: Copy ceph config to all nodes
      copy:
        src: /etc/ceph/ceph.conf
        dest: /etc/ceph/ceph.conf
        owner: root
        group: root
        mode: 0644

    - name: Start Ceph services
      service:
        name: ceph
        state: started
        enabled: true

    - name: Ensure Prometheus integration
      # Task to set up Prometheus metrics endpoint for monitoring
      # Add configurations specific to Prometheus integration
