---
- name: Provision and Configure Debian Template on Proxmox
  hosts: proxmox_host
  become: true
  vars_files:
    - ../vars/provision_vms.yml
  tasks:
    - name: Check if the Debian 12 Generic Cloud image exists
      ansible.builtin.stat:
        path: "/tmp/{{ vm_image }}"
      register: image_file

    - name: Download the Debian 12 Generic Cloud image
      ansible.builtin.shell: |
        wget --trust-server-names -P /tmp -N "{{ cloud_image_url }}"
      args:
        chdir: /tmp
      when: not image_file.stat.exists  # Skip if the image already exists

    - name: Check if the VM already exists
      ansible.builtin.shell: |
        qm list | grep -w {{ vm_id }}
      register: vm_check
      ignore_errors: true

    - name: Create a VM with the desired specifications
      ansible.builtin.shell: |
        qm create {{ vm_id }} --name {{ vm_name }} --memory {{ memory }} --net0 virtio,bridge={{ bridge }} --kvm 0
      when: vm_check.rc != 0  # Skip if the VM already exists

    - name: Check if the disk is already imported
      ansible.builtin.shell: |
        ls /var/lib/vz/images/{{ vm_id }}/vm-{{ vm_id }}-disk-0.raw
      register: disk_check
      ignore_errors: true

    - name: Import the raw disk into the ZFS storage
      ansible.builtin.shell: |
        qm importdisk {{ vm_id }} /tmp/{{ vm_image }} {{ storage }} -format {{ format }}
      when: disk_check.rc != 0  # Skip if the disk is already imported

    - name: Attach the imported disk to the VM using VirtIO SCSI
      ansible.builtin.shell: |
        qm set {{ vm_id }} --scsihw virtio-scsi-pci --scsi0 {{ storage }}:vm-{{ vm_id }}-disk-0

    - name: Set boot and display settings with serial console
      ansible.builtin.shell: |
        qm set {{ vm_id }} --boot c --bootdisk scsi0 --serial0 socket --vga serial0

    - name: Resize the disk to the specified size
      ansible.builtin.shell: |
        qm resize {{ vm_id }} scsi0 {{ disk_size }}
      when: disk_check.rc != 0  # Resize only if the disk was newly imported

    - name: Configure network for DHCP
      ansible.builtin.shell: |
        qm set {{ vm_id }} --ipconfig0 ip=dhcp

    - name: Create a cloud-init drive managed by Proxmox
      ansible.builtin.shell: |
        qm set {{ vm_id }} --ide2 {{ storage }}:cloudinit

    - name: Configure SSH access using the public key
      ansible.builtin.shell: |
        qm set {{ vm_id }} --sshkey {{ ssh_key_path }}

    - name: Specify the cloud-init configuration format
      ansible.builtin.shell: |
        qm set {{ vm_id }} --citype {{ citype }}
        qm set {{ vm_id }} --ciuser debian

    - name: Verify cloud-init configuration
      ansible.builtin.shell: |
        qm cloudinit dump {{ vm_id }} user
        qm cloudinit dump {{ vm_id }} network

    - name: Convert the VM to a template
      ansible.builtin.shell: |
        qm template {{ vm_id }}
      when: vm_check.rc != 0  # Skip if the VM is already a template

    - name: Clean up downloaded image file
      ansible.builtin.file:
        path: /tmp/{{ vm_image }}
        state: absent
      when: image_file.stat.exists  # Run cleanup if the image file exists
