- hosts: proxmox
  become: false
  gather_facts: false
  vars_files:
    - ../vars/ansible_secrets.yml  # File containing api_token_secret and api_token_id
    - ../vars/provision_vms.yml

  tasks:
    # Loop through and provision Ceph VMs using RBD storage
    - name: Provision Ceph VM
      proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ ansible_host }}"
        node: "{{ node }}"
        name: "{{ item.name }}"
        clone: "{{ item.clone }}"
        storage: "{{ item.storage }}"
        full: true
        cores: 2
        memory: 2048
        net:
          net0: virtio,bridge=vmbr0
        ostype: l26
        kvm: false
        state: started
      loop: "{{ ceph_vms }}"
      register: ceph_vm_creation

    # Add Ceph VMs to dynamic inventory
    - name: Add Ceph VM to the inventory dynamically
      add_host:
        name: "{{ item.item.name }}"
        groups: ceph
        ansible_host: "{{ item.instance.ip }}"
      loop: "{{ ceph_vm_creation.results }}"
      when: ceph_vm_creation is defined

    # Provision Docker VM using ZFS or LVM storage (choose one)
    - name: Provision Docker VM
      proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ ansible_host }}"
        node: "{{ node }}"
        name: "{{ docker_vm.name }}"
        clone: "{{ docker_vm.clone }}"
        storage: "{{ docker_vm.storage }}"
        full: true
        cores: 2
        memory: 2048
        net:
          net0: virtio,bridge=vmbr0
        ostype: l26
        kvm: false
        state: started
      register: docker_vm_creation

    - name: Wait for the VM to come up (using SSH)
      wait_for:
        host: "{{ docker_vm_creation.instance.ip }}"
        port: 22
        state: started
        delay: 10
        timeout: 300

    - name: Add the VM to the docker group dynamically
      add_host:
        name: "docker-vm"
        groups: docker
        ansible_host: "{{ docker_vm_creation.instance.ip }}"
    
    - name: Configure Docker on VMs
      include: configure_docker.yml

