- hosts: proxmox
  become: false
  gather_facts: false
  vars_files:
    - vars/ansible_secrets.yml  # File containing api_token_secret and api_token_id
    - vars/provision_vms.yml

  tasks:
    # Loop through and provision Ceph VMs using RBD storage
    - name: Provision Ceph VM
      proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ ansible_host }}"
        node: "{{ node }}"
        vmid: "{{ item.vmid }}"
        name: "{{ item.name }}"
        cores: 2
        memory: 2048
        net:
          net0: virtio,bridge=vmbr0
        ostype: l26
        kvm: false
        state: started
      loop: "{{ ceph_vms }}"

    # Provision Docker VM using ZFS or LVM storage (choose one)
    - name: Provision Docker VM
      proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ ansible_host }}"
        node: "{{ node }}"
        vmid: "{{ docker_vm.vmid }}"
        name: "{{ docker_vm.name }}"
        cores: 2
        memory: 2048
        net:
          net0: virtio,bridge=vmbr0
        ostype: l26
        kvm: false
        state: started
