all:
  hosts:
    proxmox_host:
      ansible_host: 192.168.183.190
      ansible_user: root
    ceph_cluster1:
      ansible_host: 192.168.183.
      ansible_user: root
    ceph_cluster2:
      ansible_host: 192.168.183.
      ansible_user: root
    ceph_cluster3:
      ansible_host: 192.168.183.
      ansible_user: root
    docker_host:
      ansible_host: 192.168.183.
      ansible_user: root

ceph:
  hosts:
    ceph_cluster1:
      ansible_host: 192.168.183.
      ansible_user: root
    ceph_cluster2:
      ansible_host: 192.168.183.
      ansible_user: root
    ceph_cluster3:
      ansible_host: 192.168.183.
      ansible_user: root

docker:
  hosts:
    docker_host:
        ansible_host: 192.168.183.
        ansible_user: root

proxmox:
  hosts:
    proxmox_host:
      ansible_host: 192.168.183.190
      ansible_user: ansible